export {default as Banking} from './Banking'
export {default as Commercial} from './Commercial'
export {default as Ecom} from './Ecom'
export {default as Education} from './Education'
export {default as HrServices} from './HrServices'
export {default as Warehouse} from './warehouse'
